services:
  frontend:
    build: .
    container_name: goldenduck-frontend
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - goldenduck-network
    restart: always

networks:
  goldenduck-network:
    external: true
